### ISSUE TITLE
An error meet in sfsubmit

### ISSUE THREAD

**Issue by xichaoqiang** [Zhaolun-Liu/SeisFlows-2DWD#1]
Dear Dr.Liu

I try run your code in my virtual machine.

But met an error message. The bellowing figures are the snapshots of error messages.

Can you help me fix it?

Best regards,
Xi

![image](https://user-images.githubusercontent.com/30900789/166234849-82192869-6b77-4ede-a0d1-01faaa102140.png)

The bin files had copied in the 0000 folder.

![image](https://user-images.githubusercontent.com/30900789/166235017-d50497c4-663a-497c-ab67-1d59bd22f53e.png)

The dat files have been created.

![image](https://user-images.githubusercontent.com/30900789/166235071-409e01d6-cba8-48c6-ad2e-c601d648cd70.png)

Here is the error message output in the file.

![image](https://user-images.githubusercontent.com/30900789/166235141-6ab453c7-1486-4f1e-9a7c-df50b45e96c2.png)

There is no traces data in all three folders.

![image](https://user-images.githubusercontent.com/30900789/166235231-247779eb-d848-45f3-81de-cb230f6bb8e6.png)

**Comment by Zhaolun-Liu** [comment]
It may be because of the different versions of the SPECFEM2D and the setting of Par_file has been changed. Go to folder "scratch/solver/000000", and try to run "./bin/xmeshfem2D", check the output error.

**Comment by xichaoqiang** [comment]
![image](https://user-images.githubusercontent.com/30900789/166239940-21ac0dc5-1cfd-4282-89d2-5ef69396dbad.png)

**Comment by xichaoqiang** [comment]
My used specfem2d version is your specfem2d-patch-1.

**Comment by Zhaolun-Liu** [comment]
I see. The specfem2d-patch-1 package is the latest version. So, lots of the parameters in Par_file have been changed. For example, your error indicates that "NUMBER_OF_SIMULTANEOUS_RUNS     = 1" should be added to the Par_file. There are others parameters that need to be modified. You can try to adjust the Par_file in "checker_2dwd/DATA/Par_file" according to the Par_file in "SPECFEM2D/EXAMPLES". 
I will try to update my examples late. Also, in the latest version of the specfem2d, the name of the output seismic record has been changed (see "write_seismograms.F90"). So, you need to change it either in SPECFEM2D or in Seisflow.

**Comment by Zhaolun-Liu** [comment]
Hi Xichao
Thanks for the comments. I update examples. Please check if it works now. I also upload a "write_seismograms.F90". You can replace it in your specfem2d so that you dont need to change the seisflow.

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
This problem has been fixed .
I meet an new problem.

The gpu option parameter.py is false.

![image](https://user-images.githubusercontent.com/30900789/166394046-342d49dc-7f81-41c0-be6c-757ac052aa63.png)

**Comment by Zhaolun-Liu** [comment]
you can turn off GPU mode for "xsmooth_sem" by changing 'true' to 'false' at line 277 of [SeisFlows-2DWD](https://github.com/Zhaolun-Liu/SeisFlows-2DWD)/[seisflows](https://github.com/Zhaolun-Liu/SeisFlows-2DWD/tree/main/seisflows)/[solver](https://github.com/Zhaolun-Liu/SeisFlows-2DWD/tree/main/seisflows/solver)/specfem2d.py

**Comment by xichaoqiang** [comment]
@Zhaolun-Liu 

Dear Dr.Liu

This problem has been fixed .

Inversion aborted in the fifth iteration.

I am not sure this is right.

Best regards,
Xi

![image](https://user-images.githubusercontent.com/30900789/166482585-144b1a7f-bd45-4f4a-89a7-ca5d1a49afd5.png)

**Comment by Zhaolun-Liu** [comment]
Yes. It seems right to me.

**Comment by xichaoqiang** [comment]
Dr Liu, thanks for your kindly reply.
